{% set name = "cdutil" %}
{% set version = "3.0" %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    url: https://github.com/UV-CDAT/cdutil/archive/v{{ version }}.tar.gz
    sha256: 733cb7d95d5b5d8b9d0620cb9ffc3b33de8b6b38b70b5dea06e95c2b95b5a50b
    

build:
  number: 0
  skip: True  # [win or py3k]
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - cdms2
    - numpy
    - udunits2
    - genutil

test:
  command:
    - export UVCDAT_ANONYMOUS_LOG=false && python run_tests.py -v2

about:
    home:  http://github.com/UV-CDAT/cdutil
    license: 'CCLRC'
    license_file: LICENSE
    summary: 'Climate Data Related Utitilites for the Community Data Analysis Tools'

extra:
  recipe-maintainers:
    - dnadeau4
    - doutriaux1
