{% set name = "cdutil" %}
{% set version = "8.2" %}

package:
    name: cdutil
    version: {{ version }}

source:
    url: https://github.com/CDAT/cdutil/archive/v{{ version }}.tar.gz
    sha256: 9c28ddce4cf4e3a84b1e8ca52198e07630c80a9353e951d6253971f115346c28


build:
  number: 0
  noarch: python
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools
    - cdat_info >=8.1
  run:
    - python
    - cdms2
    - genutil >=8.1.1
    - cdat_info >=8.1

test:
  commands:
    - export CDAT_ANONYMOUS_LOG=false && python -c "import cdutil"

about:
    home:  http://github.com/CDAT/cdutil
    summary: A set of tools to manipulate climate data
    license: BSD
    license_file: bsd-3-clause.txt

extra:
  recipe-maintainers:
    - dnadeau4
    - doutriaux1
