{% set name = "cdutil" %}
{% set version = "8.2.1.rc1" %}

package:
    name: cdutil
    version: {{ version }}

source:
    url: https://github.com/CDAT/cdutil/archive/v{{ version }}.tar.gz
    sha256: a1e70f8f0ca47f8a17ee20b86c21825e6353989382c1584c14fe12b9569821bb

build:
  number: 2
  noarch: python
  script: python setup.py install

requirements:
  host:
    - python
    - pip
    - setuptools
    - cdat_info
  run:
    - python
    - cdms2
    - genutil
    - cdat_info

test:
  commands:
    - python -c "import cdutil"

about:
    home: http://github.com/CDAT/cdutil
    summary: A set of tools to manipulate climate data
    license: BSD
    license_file: bsd-3-clause.txt

extra:
  recipe-maintainers:
    - dnadeau4
    - doutriaux1
    - xylar
    - downiec
    - muryanto1
    - jasonb5
