{% set name = "cdutil" %}
{% set version = "8.2.1" %}

package:
    name: cdutil
    version: {{ version }}

source:
    url: https://github.com/CDAT/cdutil/archive/v{{ version }}.tar.gz
    sha256: 9e02348ae0e9148c6b0b9391b208adf9be7d97e0da30b88518c02dfc1e07d2bf
    patches:
      - 0001-fix-version-number.patch
      - 0002-remove-numpy-mv2-float.patch

build:
  number: 5
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - cdat_info
  run:
    - python >={{ python_min }}
    - cdms2
    - genutil
    - cdat_info

test:
  requires:
    - python {{ python_min }}
  imports:
    - cdutil

about:
    home: http://github.com/CDAT/cdutil
    summary: A set of tools to manipulate climate data
    license: BSD-3-Clause
    license_file: bsd-3-clause.txt

extra:
  recipe-maintainers:
    - dnadeau4
    - doutriaux1
    - xylar
    - downiec
    - jasonb5
