{% set name = "cdutil" %}
{% set version = "8.1" %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    url: https://github.com/UV-CDAT/cdutil/archive/v{{ version }}.tar.gz
    sha256: 37d3dfa2202cab4e42a9c04cb1956dffe2146c5594fed04f6c32c91554c84b53

build:
  number: 0
  skip: True  # [win]
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools
    - cdat_info
  run:
    - python
    - cdms2
    - numpy
    - udunits2
    - genutil

test:
  commands:
    - export UVCDAT_ANONYMOUS_LOG=false && python -c "import cdutil"

about:
    home:  http://github.com/CDAT/cdutil
    license: 'CCLRC'
    license_file: LICENSE
    summary: 'Climate Data Related Utitilites for the Community Data Analysis Tools'

extra:
  recipe-maintainers:
    - dnadeau4
    - doutriaux1
