{% set name = "cdutil" %}
{% set version = "2.12" %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    url: https://github.com/UV-CDAT/cdutil/archive/v{{ version }}.tar.gz
    sha256: 18d310eac5e71180c4d5952033a3a7359685534d3f4eb827e668cc02cecc9055
    

build:
  number: 0
  skip: True  # [win or py3k]
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - cdms2
    - numpy
    - udunits2
    - genutil

test:
  commands:
    - export UVCDAT_ANONYMOUS_LOG=false && python run_tests.py -v2

about:
    home:  http://github.com/UV-CDAT/cdutil
    license: 'CCLRC'
    license_file: LICENSE
    summary: 'Climate Data Related Utitilites for the Community Data Analysis Tools'

extra:
  recipe-maintainers:
    - dnadeau4
    - doutriaux1
