travis:
  secure:
    BINSTAR_TOKEN: KDWn2PgPFHLbQ+lEQg4N4vmYEnMRRfjYx95RH5kWFoJG2pO2zZNJM/F/GZVZwhNh5LY1nc6JcmA/n+H7nVwzkFkJc5vQcQN8JVVLLjJl4erPvoDulCD1Djqe1NXyj6VaIsIL4TqqcQkKysKs67MWzTPxc7G1zGijqfGGPNafxCZLGnwfkWr1eeBxe8QG6tVhTfDFefbYxVjAkmZS8Ys0xKf7fSnWGsw1PjWZJWjLLwZjqd5aeA9zjEsRqVf91hNiBEaTPL318K/NeznJ4vfKrjt3SaJ9XcmOdfbKn/Ws5s3F0nXjxXZuhaY/25E2X5flX79w5+XdJCCbtP2LcBRuqIsZ8tLCLuF7mCMax7t9sIb3d8HnoMke5qxA9O+yYakGs6Z4UddWmqUTrbWbDIK5n04Jo0GAfSCk70hWF3wxj2qlqQyxPLUYabj15byZGxRti1zesz8gBVTKVPDegHvN76eB1NqMnEeUL9VHqu2n5hDe45dDoM8x4LEeJlDLdaeWZ0/hnk9oue9qHqhFXn0Kmpf+MwG/htLC5RM9ttmIyEkk6ULSHp8hMZvCoj/cyBjk2+jdjFJzwvwAHpL9pEdC+ZV/wPSEm6LhEMTikLNlcPduNGuMBLCUZ34AHk+TeDNVpL4XutFBiYcu5DpCphykwdK8W2jn4/iSln9ylYbwtzc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
